[package]
name = "app"
edition.workspace = true
version.workspace = true

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
connectrpc-axum = { workspace = true }
tower-http = { workspace = true }
anyhow = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
auth = { path = "../auth" }
domain = { path = "../domain" }
persistence = { path = "../persistence" }
transport = { path = "../transport" }
storage = { path = "../storage" }
mcp = { path = "../mcp" }

[dev-dependencies]
jsonwebtoken = { workspace = true }
tower = { workspace = true }
serde_json = { workspace = true }
