[package]
name = "transport"
edition.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
axum = { workspace = true }
prost = { workspace = true }
pbjson = { workspace = true }
connectrpc-axum = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
arke = { workspace = true }
auth = { path = "../auth" }
persistence = { path = "../persistence" }
domain = { path = "../domain" }
storage = { path = "../storage" }

[dev-dependencies]
tower = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }

[build-dependencies]
connectrpc-axum-build = { workspace = true }
