import { FileSpreadsheet, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { APP_NAME } from "@/lib/app-config";
import { useExportReportXlsx } from "../api/hooks";
import type { PeriodWindow } from "../types";

/** Downloads the period report as .xlsx, generated by the server. */
export function ExportExcelButton({ window }: { window: PeriodWindow }) {
  const { exportXlsx, isPending } = useExportReportXlsx();

  async function onExport() {
    try {
      const res = await exportXlsx(window, APP_NAME);
      const blob = new Blob([res.xlsx], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = res.fileName;
      a.click();
      // Revoking synchronously can cancel the download in some browsers.
      setTimeout(() => URL.revokeObjectURL(url), 0);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to export the report.");
    }
  }

  return (
    <Button variant="outline" size="sm" onClick={onExport} disabled={isPending}>
      {isPending ? <Loader2 className="animate-spin" /> : <FileSpreadsheet />} Export Excel
    </Button>
  );
}
