/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedProjectsProjectIdTimelineIndexRouteImport } from './routes/_authenticated/projects/$projectId/timeline/index'
import { Route as AuthenticatedProjectsProjectIdPagesIndexRouteImport } from './routes/_authenticated/projects/$projectId/pages/index'
import { Route as AuthenticatedProjectsProjectIdMediaIndexRouteImport } from './routes/_authenticated/projects/$projectId/media/index'
import { Route as AuthenticatedProjectsProjectIdPagesPageIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/pages/$pageId/index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdTimelineIndexRoute =
  AuthenticatedProjectsProjectIdTimelineIndexRouteImport.update({
    id: '/projects/$projectId/timeline/',
    path: '/projects/$projectId/timeline/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdPagesIndexRoute =
  AuthenticatedProjectsProjectIdPagesIndexRouteImport.update({
    id: '/projects/$projectId/pages/',
    path: '/projects/$projectId/pages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdMediaIndexRoute =
  AuthenticatedProjectsProjectIdMediaIndexRouteImport.update({
    id: '/projects/$projectId/media/',
    path: '/projects/$projectId/media/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdPagesPageIdIndexRoute =
  AuthenticatedProjectsProjectIdPagesPageIdIndexRouteImport.update({
    id: '/projects/$projectId/pages/$pageId/',
    path: '/projects/$projectId/pages/$pageId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/logout': typeof LogoutRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/media/': typeof AuthenticatedProjectsProjectIdMediaIndexRoute
  '/projects/$projectId/pages/': typeof AuthenticatedProjectsProjectIdPagesIndexRoute
  '/projects/$projectId/timeline/': typeof AuthenticatedProjectsProjectIdTimelineIndexRoute
  '/projects/$projectId/pages/$pageId/': typeof AuthenticatedProjectsProjectIdPagesPageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/media': typeof AuthenticatedProjectsProjectIdMediaIndexRoute
  '/projects/$projectId/pages': typeof AuthenticatedProjectsProjectIdPagesIndexRoute
  '/projects/$projectId/timeline': typeof AuthenticatedProjectsProjectIdTimelineIndexRoute
  '/projects/$projectId/pages/$pageId': typeof AuthenticatedProjectsProjectIdPagesPageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/logout': typeof LogoutRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/media/': typeof AuthenticatedProjectsProjectIdMediaIndexRoute
  '/_authenticated/projects/$projectId/pages/': typeof AuthenticatedProjectsProjectIdPagesIndexRoute
  '/_authenticated/projects/$projectId/timeline/': typeof AuthenticatedProjectsProjectIdTimelineIndexRoute
  '/_authenticated/projects/$projectId/pages/$pageId/': typeof AuthenticatedProjectsProjectIdPagesPageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/logout'
    | '/dashboard/'
    | '/projects/'
    | '/settings/'
    | '/projects/$projectId/'
    | '/projects/$projectId/media/'
    | '/projects/$projectId/pages/'
    | '/projects/$projectId/timeline/'
    | '/projects/$projectId/pages/$pageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/logout'
    | '/dashboard'
    | '/projects'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/media'
    | '/projects/$projectId/pages'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId/pages/$pageId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/logout'
    | '/_authenticated/dashboard/'
    | '/_authenticated/projects/'
    | '/_authenticated/settings/'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/media/'
    | '/_authenticated/projects/$projectId/pages/'
    | '/_authenticated/projects/$projectId/timeline/'
    | '/_authenticated/projects/$projectId/pages/$pageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/timeline/': {
      id: '/_authenticated/projects/$projectId/timeline/'
      path: '/projects/$projectId/timeline'
      fullPath: '/projects/$projectId/timeline/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTimelineIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/pages/': {
      id: '/_authenticated/projects/$projectId/pages/'
      path: '/projects/$projectId/pages'
      fullPath: '/projects/$projectId/pages/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/media/': {
      id: '/_authenticated/projects/$projectId/media/'
      path: '/projects/$projectId/media'
      fullPath: '/projects/$projectId/media/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMediaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/pages/$pageId/': {
      id: '/_authenticated/projects/$projectId/pages/$pageId/'
      path: '/projects/$projectId/pages/$pageId'
      fullPath: '/projects/$projectId/pages/$pageId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPagesPageIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdMediaIndexRoute: typeof AuthenticatedProjectsProjectIdMediaIndexRoute
  AuthenticatedProjectsProjectIdPagesIndexRoute: typeof AuthenticatedProjectsProjectIdPagesIndexRoute
  AuthenticatedProjectsProjectIdTimelineIndexRoute: typeof AuthenticatedProjectsProjectIdTimelineIndexRoute
  AuthenticatedProjectsProjectIdPagesPageIdIndexRoute: typeof AuthenticatedProjectsProjectIdPagesPageIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
  AuthenticatedProjectsProjectIdMediaIndexRoute:
    AuthenticatedProjectsProjectIdMediaIndexRoute,
  AuthenticatedProjectsProjectIdPagesIndexRoute:
    AuthenticatedProjectsProjectIdPagesIndexRoute,
  AuthenticatedProjectsProjectIdTimelineIndexRoute:
    AuthenticatedProjectsProjectIdTimelineIndexRoute,
  AuthenticatedProjectsProjectIdPagesPageIdIndexRoute:
    AuthenticatedProjectsProjectIdPagesPageIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
