/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedMyTasksRouteImport } from './routes/_authed/my-tasks'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedProjectsIndexRouteImport } from './routes/_authed/projects/index'
import { Route as AuthedProjectsProjectIdRouteImport } from './routes/_authed/projects/$projectId'
import { Route as AuthedSettingsTokensRouteImport } from './routes/_authed/settings/tokens'
import { Route as AuthedProjectsProjectIdIndexRouteImport } from './routes/_authed/projects/$projectId/index'
import { Route as AuthedProjectsProjectIdAllTasksRouteImport } from './routes/_authed/projects/$projectId/all-tasks'
import { Route as AuthedProjectsProjectIdMediaRouteImport } from './routes/_authed/projects/$projectId/media'
import { Route as AuthedProjectsProjectIdMembersRouteImport } from './routes/_authed/projects/$projectId/members'
import { Route as AuthedProjectsProjectIdOverviewRouteImport } from './routes/_authed/projects/$projectId/overview'
import { Route as AuthedProjectsProjectIdPagesRouteImport } from './routes/_authed/projects/$projectId/pages'
import { Route as AuthedProjectsProjectIdTimelineRouteImport } from './routes/_authed/projects/$projectId/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyTasksRoute = AuthedMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsIndexRoute = AuthedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsProjectIdRoute = AuthedProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsTokensRoute = AuthedSettingsTokensRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsProjectIdIndexRoute =
  AuthedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdAllTasksRoute =
  AuthedProjectsProjectIdAllTasksRouteImport.update({
    id: '/all-tasks',
    path: '/all-tasks',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdMediaRoute =
  AuthedProjectsProjectIdMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdMembersRoute =
  AuthedProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdOverviewRoute =
  AuthedProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdPagesRoute =
  AuthedProjectsProjectIdPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdTimelineRoute =
  AuthedProjectsProjectIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/my-tasks': typeof AuthedMyTasksRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdRouteWithChildren
  '/settings/tokens': typeof AuthedSettingsTokensRoute
  '/projects/': typeof AuthedProjectsIndexRoute
  '/projects/$projectId/all-tasks': typeof AuthedProjectsProjectIdAllTasksRoute
  '/projects/$projectId/media': typeof AuthedProjectsProjectIdMediaRoute
  '/projects/$projectId/members': typeof AuthedProjectsProjectIdMembersRoute
  '/projects/$projectId/overview': typeof AuthedProjectsProjectIdOverviewRoute
  '/projects/$projectId/pages': typeof AuthedProjectsProjectIdPagesRoute
  '/projects/$projectId/timeline': typeof AuthedProjectsProjectIdTimelineRoute
  '/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/my-tasks': typeof AuthedMyTasksRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/settings/tokens': typeof AuthedSettingsTokensRoute
  '/projects': typeof AuthedProjectsIndexRoute
  '/projects/$projectId/all-tasks': typeof AuthedProjectsProjectIdAllTasksRoute
  '/projects/$projectId/media': typeof AuthedProjectsProjectIdMediaRoute
  '/projects/$projectId/members': typeof AuthedProjectsProjectIdMembersRoute
  '/projects/$projectId/overview': typeof AuthedProjectsProjectIdOverviewRoute
  '/projects/$projectId/pages': typeof AuthedProjectsProjectIdPagesRoute
  '/projects/$projectId/timeline': typeof AuthedProjectsProjectIdTimelineRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/my-tasks': typeof AuthedMyTasksRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/projects/$projectId': typeof AuthedProjectsProjectIdRouteWithChildren
  '/_authed/settings/tokens': typeof AuthedSettingsTokensRoute
  '/_authed/projects/': typeof AuthedProjectsIndexRoute
  '/_authed/projects/$projectId/all-tasks': typeof AuthedProjectsProjectIdAllTasksRoute
  '/_authed/projects/$projectId/media': typeof AuthedProjectsProjectIdMediaRoute
  '/_authed/projects/$projectId/members': typeof AuthedProjectsProjectIdMembersRoute
  '/_authed/projects/$projectId/overview': typeof AuthedProjectsProjectIdOverviewRoute
  '/_authed/projects/$projectId/pages': typeof AuthedProjectsProjectIdPagesRoute
  '/_authed/projects/$projectId/timeline': typeof AuthedProjectsProjectIdTimelineRoute
  '/_authed/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/dashboard'
    | '/my-tasks'
    | '/admin/users'
    | '/projects/$projectId'
    | '/settings/tokens'
    | '/projects/'
    | '/projects/$projectId/all-tasks'
    | '/projects/$projectId/media'
    | '/projects/$projectId/members'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/pages'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/dashboard'
    | '/my-tasks'
    | '/admin/users'
    | '/settings/tokens'
    | '/projects'
    | '/projects/$projectId/all-tasks'
    | '/projects/$projectId/media'
    | '/projects/$projectId/members'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/pages'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/setup'
    | '/_authed/dashboard'
    | '/_authed/my-tasks'
    | '/_authed/admin/users'
    | '/_authed/projects/$projectId'
    | '/_authed/settings/tokens'
    | '/_authed/projects/'
    | '/_authed/projects/$projectId/all-tasks'
    | '/_authed/projects/$projectId/media'
    | '/_authed/projects/$projectId/members'
    | '/_authed/projects/$projectId/overview'
    | '/_authed/projects/$projectId/pages'
    | '/_authed/projects/$projectId/timeline'
    | '/_authed/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my-tasks': {
      id: '/_authed/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof AuthedMyTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/': {
      id: '/_authed/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthedProjectsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId': {
      id: '/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthedProjectsProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/tokens': {
      id: '/_authed/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof AuthedSettingsTokensRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/': {
      id: '/_authed/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/all-tasks': {
      id: '/_authed/projects/$projectId/all-tasks'
      path: '/all-tasks'
      fullPath: '/projects/$projectId/all-tasks'
      preLoaderRoute: typeof AuthedProjectsProjectIdAllTasksRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/media': {
      id: '/_authed/projects/$projectId/media'
      path: '/media'
      fullPath: '/projects/$projectId/media'
      preLoaderRoute: typeof AuthedProjectsProjectIdMediaRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/members': {
      id: '/_authed/projects/$projectId/members'
      path: '/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof AuthedProjectsProjectIdMembersRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/overview': {
      id: '/_authed/projects/$projectId/overview'
      path: '/overview'
      fullPath: '/projects/$projectId/overview'
      preLoaderRoute: typeof AuthedProjectsProjectIdOverviewRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/pages': {
      id: '/_authed/projects/$projectId/pages'
      path: '/pages'
      fullPath: '/projects/$projectId/pages'
      preLoaderRoute: typeof AuthedProjectsProjectIdPagesRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/timeline': {
      id: '/_authed/projects/$projectId/timeline'
      path: '/timeline'
      fullPath: '/projects/$projectId/timeline'
      preLoaderRoute: typeof AuthedProjectsProjectIdTimelineRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
  }
}

interface AuthedProjectsProjectIdRouteChildren {
  AuthedProjectsProjectIdAllTasksRoute: typeof AuthedProjectsProjectIdAllTasksRoute
  AuthedProjectsProjectIdMediaRoute: typeof AuthedProjectsProjectIdMediaRoute
  AuthedProjectsProjectIdMembersRoute: typeof AuthedProjectsProjectIdMembersRoute
  AuthedProjectsProjectIdOverviewRoute: typeof AuthedProjectsProjectIdOverviewRoute
  AuthedProjectsProjectIdPagesRoute: typeof AuthedProjectsProjectIdPagesRoute
  AuthedProjectsProjectIdTimelineRoute: typeof AuthedProjectsProjectIdTimelineRoute
  AuthedProjectsProjectIdIndexRoute: typeof AuthedProjectsProjectIdIndexRoute
}

const AuthedProjectsProjectIdRouteChildren: AuthedProjectsProjectIdRouteChildren =
  {
    AuthedProjectsProjectIdAllTasksRoute: AuthedProjectsProjectIdAllTasksRoute,
    AuthedProjectsProjectIdMediaRoute: AuthedProjectsProjectIdMediaRoute,
    AuthedProjectsProjectIdMembersRoute: AuthedProjectsProjectIdMembersRoute,
    AuthedProjectsProjectIdOverviewRoute: AuthedProjectsProjectIdOverviewRoute,
    AuthedProjectsProjectIdPagesRoute: AuthedProjectsProjectIdPagesRoute,
    AuthedProjectsProjectIdTimelineRoute: AuthedProjectsProjectIdTimelineRoute,
    AuthedProjectsProjectIdIndexRoute: AuthedProjectsProjectIdIndexRoute,
  }

const AuthedProjectsProjectIdRouteWithChildren =
  AuthedProjectsProjectIdRoute._addFileChildren(
    AuthedProjectsProjectIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMyTasksRoute: typeof AuthedMyTasksRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedProjectsProjectIdRoute: typeof AuthedProjectsProjectIdRouteWithChildren
  AuthedSettingsTokensRoute: typeof AuthedSettingsTokensRoute
  AuthedProjectsIndexRoute: typeof AuthedProjectsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMyTasksRoute: AuthedMyTasksRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedProjectsProjectIdRoute: AuthedProjectsProjectIdRouteWithChildren,
  AuthedSettingsTokensRoute: AuthedSettingsTokensRoute,
  AuthedProjectsIndexRoute: AuthedProjectsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
